from __future__ import annotations

from typing import Callable, Sequence, TextIO

import click

from sentry.backup.comparators import get_default_comparators
from sentry.backup.findings import Finding, FindingJSONEncoder
from sentry.backup.helpers import ImportFlags
from sentry.backup.validate import validate
from sentry.runner.decorators import configuration
from sentry.utils import json

DEFAULT_INDENT = 2

MERGE_USERS_HELP = """If this flag is set and users in the import JSON have matching usernames to
                   those already in the database, the existing users are used instead and their
                   associated user scope models are not updated. If this flag is not set, new users
                   are always created in the event of a collision, with the new user receiving a
                   random suffix to their username."""

OVERWRITE_CONFIGS_HELP = """Imports are generally non-destructive of old data. However, if this flag
                         is set and a global configuration, like an option or a relay id, collides
                         with an existing value, the new value will overwrite the existing one. If
                         the flag is left in its (default) unset state, the old value will be
                         retained in the event of a collision."""

FINDINGS_FILE_HELP = """Optional file that records error findings, saved in the JSON format.
                     If left unset, no such file is written."""


def get_printer(silent: bool) -> Callable:
    if silent:
        return lambda *args, **kwargs: None
    else:
        return click.echo


def parse_filter_arg(filter_arg: str) -> set[str] | None:
    filter_by = None
    if filter_arg:
        filter_by = set(filter_arg.split(","))

    return filter_by


def write_findings(
    findings_file: TextIO | None, findings: Sequence[Finding], indent: int, printer: Callable
):
    for f in findings:
        printer(f.pretty(), err=True)

    if findings_file:
        findings_encoder = FindingJSONEncoder(
            sort_keys=True,
            ensure_ascii=True,
            check_circular=True,
            allow_nan=True,
            indent=indent,
            encoding="utf-8",
        )

        with findings_file as file:
            encoded = findings_encoder.encode(findings)
            file.write(encoded)


@click.command(name="compare")
@click.argument("left", type=click.File("rb"))
@click.argument("right", type=click.File("rb"))
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@configuration
def compare(left, right, findings_file):
    """
    Compare two exports generated by the `export` command for equality, modulo certain necessary changed like `date_updated` timestamps, unique tokens, and the like.
    """

    with left:
        try:
            left_data = json.load(left)
        except json.JSONDecodeError:
            click.echo("Invalid left JSON", err=True)

    with right:
        try:
            right_data = json.load(right)
        except json.JSONDecodeError:
            click.echo("Invalid right JSON", err=True)

    res = validate(left_data, right_data, get_default_comparators())
    if res:
        write_findings(findings_file, res.findings, DEFAULT_INDENT, click.echo)  # type: ignore
        click.echo(f"Done, found {len(res.findings)} differences:\n\n{res.pretty()}")
    else:
        click.echo("Done, found 0 differences!")


@click.group(name="import")
def import_():
    """Performs non-destructive imports of core data for a Sentry installation."""


@import_.command(name="users")
@click.argument("src", type=click.File("rb"))
@click.option(
    "--filter_usernames",
    default="",
    type=str,
    help="An optional comma-separated list of users to include. "
    "If this option is not set, all encountered users are imported.",
)
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--merge_users",
    default=False,
    is_flag=True,
    help=MERGE_USERS_HELP,
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def import_users(src, filter_usernames, findings_file, merge_users, silent):
    """
    Import the Sentry users from an exported JSON file.
    """

    from sentry.backup.imports import ImportingError, import_in_user_scope

    printer = get_printer(silent)
    try:
        import_in_user_scope(
            src,
            flags=ImportFlags(merge_users=merge_users),
            user_filter=parse_filter_arg(filter_usernames),
            printer=printer,
        )
    except ImportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@import_.command(name="organizations")
@click.argument("src", type=click.File("rb"))
@click.option(
    "--filter_org_slugs",
    default="",
    type=str,
    help="An optional comma-separated list of organization slugs to include. "
    "If this option is not set, all encountered organizations are imported. "
    "Users not members of at least one organization in this set will not be imported.",
)
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--merge_users",
    default=False,
    is_flag=True,
    help=MERGE_USERS_HELP,
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def import_organizations(src, filter_org_slugs, findings_file, merge_users, silent):
    """
    Import the Sentry organizations, and all constituent Sentry users, from an exported JSON file.
    """

    from sentry.backup.imports import ImportingError, import_in_organization_scope

    printer = get_printer(silent)
    try:
        import_in_organization_scope(
            src,
            flags=ImportFlags(merge_users=merge_users),
            org_filter=parse_filter_arg(filter_org_slugs),
            printer=printer,
        )
    except ImportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@import_.command(name="config")
@click.argument("src", type=click.File("rb"))
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--merge_users",
    default=False,
    is_flag=True,
    help=MERGE_USERS_HELP,
)
@click.option(
    "--overwrite_configs",
    default=False,
    is_flag=True,
    help=OVERWRITE_CONFIGS_HELP,
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def import_config(src, findings_file, merge_users, overwrite_configs, silent):
    """
    Import all configuration and administrator accounts needed to set up this Sentry instance.
    """

    from sentry.backup.imports import ImportingError, import_in_config_scope

    printer = get_printer(silent)
    try:
        import_in_config_scope(
            src,
            flags=ImportFlags(merge_users=merge_users, overwrite_configs=overwrite_configs),
            printer=printer,
        )
    except ImportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@import_.command(name="global")
@click.argument("src", type=click.File("rb"))
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--overwrite_configs",
    default=False,
    is_flag=True,
    help=OVERWRITE_CONFIGS_HELP,
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def import_global(src, findings_file, overwrite_configs, silent):
    """
    Import all Sentry data from an exported JSON file.
    """

    from sentry.backup.imports import ImportingError, import_in_global_scope

    printer = get_printer(silent)
    try:
        import_in_global_scope(
            src,
            flags=ImportFlags(overwrite_configs=overwrite_configs),
            printer=printer,
        )
    except ImportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@click.group(name="export")
def export():
    """Exports core data for the Sentry installation."""


@export.command(name="users")
@click.argument("dest", default="-", type=click.File("w"))
@click.option(
    "--filter_usernames",
    default="",
    type=str,
    help="An optional comma-separated list of users to include. "
    "If this option is not set, all encountered users are imported.",
)
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--indent",
    default=2,
    type=int,
    help="Number of spaces to indent for the JSON output. (default: 2)",
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def export_users(dest, filter_usernames, findings_file, indent, silent):
    """
    Export all Sentry users in the JSON format.
    """

    from sentry.backup.exports import ExportingError, export_in_user_scope

    printer = get_printer(silent)
    try:
        export_in_user_scope(
            dest,
            indent=indent,
            user_filter=parse_filter_arg(filter_usernames),
            printer=printer,
        )
    except ExportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@export.command(name="organizations")
@click.argument("dest", default="-", type=click.File("w"))
@click.option(
    "--filter_org_slugs",
    default="",
    type=str,
    help="An optional comma-separated list of organization slugs to include. "
    "If this option is not set, all encountered organizations are exported. "
    "Users not members of at least one organization in this set will not be exported.",
)
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--indent",
    default=2,
    type=int,
    help="Number of spaces to indent for the JSON output. (default: 2)",
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def export_organizations(dest, filter_org_slugs, findings_file, indent, silent):
    """
    Export all Sentry organizations, and their constituent users, in the JSON format.
    """

    from sentry.backup.exports import ExportingError, export_in_organization_scope

    printer = get_printer(silent)
    try:
        export_in_organization_scope(
            dest,
            indent=indent,
            org_filter=parse_filter_arg(filter_org_slugs),
            printer=printer,
        )
    except ExportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@export.command(name="config")
@click.argument("dest", default="-", type=click.File("w"))
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--indent",
    default=2,
    type=int,
    help="Number of spaces to indent for the JSON output. (default: 2)",
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def export_config(dest, findings_file, indent, silent):
    """
    Export all configuration and administrator accounts needed to set up this Sentry instance.
    """

    from sentry.backup.exports import ExportingError, export_in_config_scope

    printer = get_printer(silent)
    try:
        export_in_config_scope(
            dest,
            indent=indent,
            printer=printer,
        )
    except ExportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e


@export.command(name="global")
@click.argument("dest", default="-", type=click.File("w"))
@click.option(
    "--findings_file",
    type=click.File("w"),
    required=False,
    help=FINDINGS_FILE_HELP,
)
@click.option(
    "--indent",
    default=2,
    type=int,
    help="Number of spaces to indent for the JSON output. (default: 2)",
)
@click.option("--silent", "-q", default=False, is_flag=True, help="Silence all debug output.")
@configuration
def export_global(dest, findings_file, indent, silent):
    """
    Export all Sentry data in the JSON format.
    """

    from sentry.backup.exports import ExportingError, export_in_global_scope

    printer = get_printer(silent)
    try:
        export_in_global_scope(
            dest,
            indent=indent,
            printer=printer,
        )
    except ExportingError as e:
        if e.context:
            write_findings(findings_file, [e.context], 2, printer)
        raise e
